### ISSUE TITLE
Same problem with rising EOF

### ISSUE THREAD

**Issue by matlas-zz** [swdunlop/AndBug#14]
It runs on MAC, no other known debuggers running, target is Android 4.3 tablet, adb shell works, debugging support in settings enabled.

./andbug shell -d C5OKCT042449  -p com.android.settings
!! EOF
Traceback (most recent call last):
  File "./andbug", line 34, in main
    andbug.command.run_command(args)
  File "/Users/matlas/cvc/AndBug/lib/andbug/command.py", line 220, in run_command
    return ctxt.perform(args[0], args[1:])
  File "/Users/matlas/cvc/AndBug/lib/andbug/command.py", line 150, in perform
    if act.proc: self.connect()
  File "/Users/matlas/cvc/AndBug/lib/andbug/command.py", line 60, in connect
    self.sess = andbug.vm.connect(self.pid, self.dev)
  File "/Users/matlas/cvc/AndBug/lib/andbug/vm.py", line 1157, in connect
    conn = andbug.proto.connect(andbug.proto.forward(pid, dev))
  File "/Users/matlas/cvc/AndBug/lib/andbug/proto.py", line 97, in connect
    p.start()
  File "/Users/matlas/cvc/AndBug/lib/andbug/proto.py", line 278, in start
    self.readHandshake()
  File "/Users/matlas/cvc/AndBug/lib/andbug/proto.py", line 162, in readHandshake
    data = self.read(len(HANDSHAKE_MSG))
  File "/Users/matlas/cvc/AndBug/lib/andbug/proto.py", line 132, in read
    pkt = self._read(sz)
  File "/Users/matlas/cvc/AndBug/lib/andbug/proto.py", line 80, in read
    if not pkt: raise EOF()
EOF: EOF

**Comment by matlas-zz** [comment]
Sorry, it works with another projects, closing issue. BTW, thanks for very good tool.

**Comment by swdunlop** [comment]
Glad to see it sorted out. :)

**Comment by zhiqiangxu** [comment]
The same problem here:

$ andbug shell -d emulator-5554 -p com.android.settings
!! EOF
Traceback (most recent call last):
  File "/usr/local/bin/andbug", line 34, in main
    andbug.command.run_command(args)
  File "/Library/Python/2.7/site-packages/andbug/command.py", line 220, in run_command
    return ctxt.perform(args[0], args[1:])
  File "/Library/Python/2.7/site-packages/andbug/command.py", line 150, in perform
    if act.proc: self.connect()
  File "/Library/Python/2.7/site-packages/andbug/command.py", line 60, in connect
    self.sess = andbug.vm.connect(self.pid, self.dev)
  File "/Library/Python/2.7/site-packages/andbug/vm.py", line 1157, in connect
    conn = andbug.proto.connect(andbug.proto.forward(pid, dev))
  File "/Library/Python/2.7/site-packages/andbug/proto.py", line 97, in connect
    p.start()
  File "/Library/Python/2.7/site-packages/andbug/proto.py", line 278, in start
    self.readHandshake()
  File "/Library/Python/2.7/site-packages/andbug/proto.py", line 162, in readHandshake
    data = self.read(len(HANDSHAKE_MSG))
  File "/Library/Python/2.7/site-packages/andbug/proto.py", line 132, in read
    pkt = self._read(sz)
  File "/Library/Python/2.7/site-packages/andbug/proto.py", line 80, in read
    if not pkt: raise EOF()
EOF: EOF

**Comment by ramappyhigh** [comment]
!! EOF
Traceback (most recent call last):
  File "/usr/local/bin/andbug", line 34, in main
    andbug.command.run_command(args)
  File "/usr/local/lib/python2.7/dist-packages/andbug/command.py", line 220, in run_command
    return ctxt.perform(args[0], args[1:])
  File "/usr/local/lib/python2.7/dist-packages/andbug/command.py", line 150, in perform
    if act.proc: self.connect()
  File "/usr/local/lib/python2.7/dist-packages/andbug/command.py", line 60, in connect
    self.sess = andbug.vm.connect(self.pid, self.dev)
  File "/usr/local/lib/python2.7/dist-packages/andbug/vm.py", line 1157, in connect
    conn = andbug.proto.connect(andbug.proto.forward(pid, dev))
  File "/usr/local/lib/python2.7/dist-packages/andbug/proto.py", line 97, in connect
    p.start()
  File "/usr/local/lib/python2.7/dist-packages/andbug/proto.py", line 278, in start
    self.readHandshake()
  File "/usr/local/lib/python2.7/dist-packages/andbug/proto.py", line 162, in readHandshake
    data = self.read(len(HANDSHAKE_MSG))
  File "/usr/local/lib/python2.7/dist-packages/andbug/proto.py", line 132, in read
    pkt = self._read(sz)
  File "/usr/local/lib/python2.7/dist-packages/andbug/proto.py", line 80, in read
    if not pkt: raise EOF()
EOF: EOF
