### ISSUE TITLE
Add Q/A to "Common Problems" in Readme

### ISSUE THREAD

**Issue by fbarriga** [swdunlop/AndBug#2]
Q:  I get this error:

Traceback (most recent call last):
  File "./andbug", line 28, in main
    andbug.command.run_command(args)
  File "/home/felipe/AndBug/lib/andbug/command.py", line 220, in run_command
    return ctxt.perform(args[0], args[1:])
  File "/home/felipe/AndBug/lib/andbug/command.py", line 150, in perform
    if act.proc: self.connect()
  File "/home/felipe/AndBug/lib/andbug/command.py", line 60, in connect
    self.sess = andbug.vm.connect(self.pid, self.dev)
  File "/home/felipe/AndBug/lib/andbug/vm.py", line 921, in connect
    conn = andbug.proto.connect(andbug.proto.forward(pid, dev))
  File "/home/felipe/AndBug/lib/andbug/proto.py", line 97, in connect
    p.start()
  File "/home/felipe/AndBug/lib/andbug/proto.py", line 278, in start
    self.readHandshake()
  File "/home/felipe/AndBug/lib/andbug/proto.py", line 162, in readHandshake
    data = self.read(len(HANDSHAKE_MSG))
  File "/home/felipe/AndBug/lib/andbug/proto.py", line 132, in read
    pkt = self._read(sz)
  File "/home/felipe/AndBug/lib/andbug/proto.py", line 80, in read
    if not pkt: raise EOF()
EOF: EOF

A: You can't run AndBug with DDMS running. Try shutting it down first.

**Comment by swdunlop** [comment]
Updated, thank you for the heads up.
