### ISSUE TITLE
andbug erro 

### ISSUE THREAD

**Issue by ghost** [swdunlop/AndBug#20]
Hello ! When I first  use Andbug , I get some error . The fellow is the description of the erros:
~$ andbug shell -p 2785
!! [Errno 104] Connection reset by peer
Traceback (most recent call last):
  File "/home/tiankai/git-hub/AndBug/andbug", line 34, in main
    andbug.command.run_command(args)
  File "/usr/local/lib/python2.7/dist-packages/andbug/command.py", line 220, in run_command
    return ctxt.perform(args[0], args[1:])
  File "/usr/local/lib/python2.7/dist-packages/andbug/command.py", line 150, in perform
    if act.proc: self.connect()
  File "/usr/local/lib/python2.7/dist-packages/andbug/command.py", line 60, in connect
    self.sess = andbug.vm.connect(self.pid, self.dev)
  File "/usr/local/lib/python2.7/dist-packages/andbug/vm.py", line 1157, in connect
    conn = andbug.proto.connect(andbug.proto.forward(pid, dev))
  File "/usr/local/lib/python2.7/dist-packages/andbug/proto.py", line 97, in connect
    p.start()
  File "/usr/local/lib/python2.7/dist-packages/andbug/proto.py", line 278, in start
    self.readHandshake()
  File "/usr/local/lib/python2.7/dist-packages/andbug/proto.py", line 162, in readHandshake
    data = self.read(len(HANDSHAKE_MSG))
  File "/usr/local/lib/python2.7/dist-packages/andbug/proto.py", line 132, in read
    pkt = self._read(sz)
  File "/usr/local/lib/python2.7/dist-packages/andbug/proto.py", line 79, in read
    pkt = conn.recv(req)
error: [Errno 104] Connection reset by peer

I don know how to fix it. So I want get your help ! thank!

**Comment by somebody365** [comment]
It works well when I use emulator, but I have the same problem when using real phone device. Could you help me? Thank you!

**Comment by somebody365** [comment]
I know the reason.Because if you want to use AndBug to debug app, your phone must be the debug version(ro.debuggable = 1), or the app‘s android:debuggable="true"

**Comment by tunsuy** [comment]
@somebody365 ，it doesn't work when i do it like you said。Could you help me? Thank you!

**Comment by xingchch** [comment]
Try to root your device first.

**Comment by dk201996** [comment]
same problem with a rooted Android 6.0
!! [Errno 104] Connection reset by peer
Traceback (most recent call last):
  File "/usr/local/bin/andbug", line 34, in main
    andbug.command.run_command(args)
  File "/usr/local/lib/python2.7/dist-packages/andbug/command.py", line 220, in run_command
    return ctxt.perform(args[0], args[1:])
  File "/usr/local/lib/python2.7/dist-packages/andbug/command.py", line 150, in perform
    if act.proc: self.connect()
  File "/usr/local/lib/python2.7/dist-packages/andbug/command.py", line 60, in connect
    self.sess = andbug.vm.connect(self.pid, self.dev)
  File "/usr/local/lib/python2.7/dist-packages/andbug/vm.py", line 1157, in connect
    conn = andbug.proto.connect(andbug.proto.forward(pid, dev))
  File "/usr/local/lib/python2.7/dist-packages/andbug/proto.py", line 97, in connect
    p.start()
  File "/usr/local/lib/python2.7/dist-packages/andbug/proto.py", line 278, in start
    self.readHandshake()
  File "/usr/local/lib/python2.7/dist-packages/andbug/proto.py", line 162, in readHandshake
    data = self.read(len(HANDSHAKE_MSG))
  File "/usr/local/lib/python2.7/dist-packages/andbug/proto.py", line 132, in read
    pkt = self._read(sz)
  File "/usr/local/lib/python2.7/dist-packages/andbug/proto.py", line 79, in read
    pkt = conn.recv(req)
error: [Errno 104] Connection reset by peer

root@kali:~# andbug shell -p 15543
!! [Errno 104] Connection reset by peer
Traceback (most recent call last):
  File "/usr/local/bin/andbug", line 34, in main
    andbug.command.run_command(args)
  File "/usr/local/lib/python2.7/dist-packages/andbug/command.py", line 220, in run_command
    return ctxt.perform(args[0], args[1:])
  File "/usr/local/lib/python2.7/dist-packages/andbug/command.py", line 150, in perform
    if act.proc: self.connect()
  File "/usr/local/lib/python2.7/dist-packages/andbug/command.py", line 60, in connect
    self.sess = andbug.vm.connect(self.pid, self.dev)
  File "/usr/local/lib/python2.7/dist-packages/andbug/vm.py", line 1157, in connect
    conn = andbug.proto.connect(andbug.proto.forward(pid, dev))
  File "/usr/local/lib/python2.7/dist-packages/andbug/proto.py", line 97, in connect
    p.start()
  File "/usr/local/lib/python2.7/dist-packages/andbug/proto.py", line 278, in start
    self.readHandshake()
  File "/usr/local/lib/python2.7/dist-packages/andbug/proto.py", line 162, in readHandshake
    data = self.read(len(HANDSHAKE_MSG))
  File "/usr/local/lib/python2.7/dist-packages/andbug/proto.py", line 132, in read
    pkt = self._read(sz)
  File "/usr/local/lib/python2.7/dist-packages/andbug/proto.py", line 79, in read
    pkt = conn.recv(req)
error: [Errno 104] Connection reset by peer
