### ISSUE TITLE
!! [Errno 32] Broken pipe 

### ISSUE THREAD

**Issue by xingchch** [swdunlop/AndBug#24]
Does this tool only works  on rooted device? I tried this on rooted device and it works fine ,but on one unrooted device, it reported errors like below:

! [Errno 32] Broken pipe
Traceback (most recent call last):
  File "./andbug", line 34, in main
    andbug.command.run_command(args)
  File "/usr/local/lib/python2.7/dist-packages/andbug/command.py", line 220, in run_command
    return ctxt.perform(args[0], args[1:])
  File "/usr/local/lib/python2.7/dist-packages/andbug/command.py", line 150, in perform
    if act.proc: self.connect()
  File "/usr/local/lib/python2.7/dist-packages/andbug/command.py", line 60, in connect
    self.sess = andbug.vm.connect(self.pid, self.dev)
  File "/usr/local/lib/python2.7/dist-packages/andbug/vm.py", line 1157, in connect
    conn = andbug.proto.connect(andbug.proto.forward(pid, dev))
  File "/usr/local/lib/python2.7/dist-packages/andbug/proto.py", line 97, in connect
    p.start()
  File "/usr/local/lib/python2.7/dist-packages/andbug/proto.py", line 277, in start
    self.writeHandshake()
  File "/usr/local/lib/python2.7/dist-packages/andbug/proto.py", line 168, in writeHandshake
    return self.write(HANDSHAKE_MSG)
  File "/usr/local/lib/python2.7/dist-packages/andbug/proto.py", line 94, in write
    raise EOF(exc)
EOF: [Errno 32] Broken pipe

**Comment by xingchch** [comment]
yes, you'd better root your devices first.
